name = "malfoid-talk-api"
main = "worker.js"
compatibility_date = "2026-10-09"
workers_dev = true

[[ratelimits]]
name = "RATE_LIMITER"
namespace_id = "18422010"

[ratelimits.simple]
limit = 10
period = 60
[observability]
enabled = true

[observability.logs]
enabled = true
invocation_logs = true
persist = true
